apiVersion: v2
name: globex-skupper
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: globex-store-app
    version: 0.1.0
    repository: file://globex-store-app
  - name: globex-db-secret
    version: 0.1.0
    repository: file://globex-db-secret
  - name: globex-web
    version: 0.1.0
    repository: file://globex-web
  - name: globex-db
    version: 0.1.0
    repository: file://globex-db
    condition: skupper.deploy
  - name: networkpolicy
    version: 0.1.0
    repository: file://networkpolicy
    condition: skupper.deploy
