replicaCount: 1

image:
  repository: quay.io/cloud-architecture-workshop/order-aggregator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 8080
  containerPort: 8080
  portName: http

route:
  enabled: false
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect    

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /q/health/live
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /q/health/ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3

podSecurityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

kafka:
  bootstrapServer: ""
  securityProtocol: ""
  saslMechanism: ""
  clientId: ""
  clientSecret: ""
  streams:
    topics: order.updates.public.orders, order.updates.public.line_item, globex.order-aggregated
    replicationFactor: 2
    commitIntervalMs: 10000
    applicationId: globex-cdc
  topics:
    orderChangeEvent: order.updates.public.orders
    lineItemChangeEvent: order.updates.public.line_item
    aggregatedOrder: globex.order-aggregated
