kind: Secret
apiVersion: v1
metadata:
  name: {{ include "datagrid.name" . }}-identities
  labels:
    {{- include "datagrid.labels" . | nindent 4 }}
stringData:
  identities.yaml: |
    credentials:
      - username: {{ .Values.identities.username }}
        password: {{ .Values.identities.password }}
type: Opaque
