apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ .Values.inventoryService.name }}
    app.kubernetes.io/part-of: app-inventory
  name: {{ .Values.inventoryService.name }}
spec:
  ports:
  - name: {{ .Values.inventoryService.service.portName }}
    port: {{ .Values.inventoryService.service.port }}
    protocol: TCP
    targetPort: {{ .Values.inventoryService.ports.httpPortName }}
  selector:
    app.kubernetes.io/name: {{ .Values.inventoryService.name }}

