apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "amq-broker.name" . }}-hook
  labels:
    {{- include "amq-broker.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.hook.argocd.enabled }}
    {{- include "amq-broker.hook.argocd-syncwave" . | nindent 4 }}
    {{- else }}
    "helm.sh/hook": pre-install
    {{- end }}
