apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datagrid.name" . }}-hook
  labels:
    {{- include "datagrid.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.hook.argocd.enabled }}
    {{- include "datagrid.hook.argocd-syncwave" . | nindent 4 }}
    {{- else }}
    "helm.sh/hook": post-install
    {{- end }}
