apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "datagrid.name" . }}-hook
  labels:
    {{- include "datagrid.labels" . | nindent 4 }}
  annotations: 
    {{- if .Values.hook.argocd.enabled }}
    {{- include "datagrid.hook.argocd-syncwave" . | nindent 4 }}
    {{- else }}
    "helm.sh/hook": post-install
    {{- end }}
spec:
  selector: {}
  template:
    metadata:
      name: {{ include "datagrid.name" . }}-hook
    spec:
      serviceAccountName: {{ include "datagrid.name" . }}-hook
      securityContext:
        {{- toYaml .Values.hook.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.hook.securityContext | nindent 12 }}
          image: "{{ .Values.hook.image.repository }}:{{ .Values.hook.image.tag }}"
          imagePullPolicy: {{ .Values.hook.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DATAGRID_CR_NAME
              value: {{ .Values.datagrid.name }}
            - name: TRUSTSTORE_NAME
              value: {{ .Values.truststore.name }}
      restartPolicy: Never