apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-aggregator.name" . }}
  labels:
    {{- include "order-aggregator.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    quarkus.kafka-streams.bootstrap-servers={{ include "kafka.bootstrap-server" . }}

    {{- if ( include "kafka.authentication" .) }}
    quarkus.kafka-streams.security.protocol={{ include "kafka.security-protocol" . }}
    quarkus.kafka-streams.sasl.mechanism={{ include "kafka.sasl-mechanism" . }}
    {{ end }}

    {{ if eq (include "kafka.sasl-mechanism" .) "PLAIN" }}
    quarkus.kafka-streams.sasl.jaas-config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      username="{{ include "kafka.client-id" . }}" \
      password="{{ include "kafka.client-secret" . }}" ;
    {{ end }}

    quarkus.kafka-streams.application-id={{ .Values.kafka.streams.applicationId }}

    quarkus.kafka-streams.topics={{ .Values.kafka.streams.topics }}

    quarkus.kafka-streams.commit.interval.ms={{ .Values.kafka.streams.commitIntervalMs }}

    kafka-streams.replication.factor={{ .Values.kafka.streams.replicationFactor }}

    topic.order-change-event={{ .Values.kafka.topics.orderChangeEvent }}
    topic.lineitem-change-event={{ .Values.kafka.topics.lineItemChangeEvent }}
    topic.aggregate-order={{ .Values.kafka.topics.aggregatedOrder }}
