replicaCount: 1

image:
  repository: quay.io/redhatintegration/rocket.chat
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "6.2.0"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 3000

route:
  enabled: true
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /api/v1/info
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /api/v1/info
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

resources: {}

rocketchat:
  admin:
    username: rocketchat-admin
    password: rocketchat
    email: admin@example.com

mongodb:
  username:
  password:
  service:
  port: 27017
  database: rocketchat

