kind: Secret
apiVersion: v1
metadata:
  name: {{ include "order-db.name" . }}
  labels:
    {{- include "order-db.labels" . | nindent 4 }}
  annotations:
    {{- include "order-db.argocd-syncwave" . | nindent 4 }}
data:
  database-user: {{ .Values.pgsql.user | b64enc }}
  database-password: {{ .Values.pgsql.password | b64enc }}
  database-name: {{ .Values.pgsql.database | b64enc}}
  database-admin-password: {{ include "order-db.admin-password" . }}
type: Opaque
