{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "order-db.serviceAccountName" . }}
  labels:
    {{- include "order-db.labels" . | nindent 4 }}
  annotations:
    {{- include "order-db.argocd-syncwave" . | nindent 4 }}
{{- end }}
