apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "matrix-secret.name" . }}
  labels:
    {{- include "matrix-secret.labels" . | nindent 4 }}    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: matrix-secret-job
  namespace: {{ .Release.Namespace }}
