apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cashback-connector.name" . }}
  labels:
    {{- include "cashback-connector.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    camel.component.kafka.brokers={{ include "kafka.bootstrap-server" . }}

    {{- if ( include "kafka.authentication" .) }}
    camel.component.kafka.securityprotocol={{ include "kafka.security-protocol" . }}
    camel.component.kafka.saslmechanism={{ include "kafka.sasl-mechanism" . }}
    {{- end }}

    {{- if eq (include "kafka.sasl-mechanism" .) "PLAIN" }}
    camel.component.kafka.sasljaasconfig=org.apache.kafka.common.security.plain.PlainLoginModule required username="{{ include "kafka.client-id" . }}" password="{{ include "kafka.client-secret" . }}" ;
    {{- end }}
    
    quarkus.datasource.cashback.jdbc.url=${DATASOURCE_JDBC_URL}
    quarkus.datasource.cashback.username=${DATASOURCE_USERNAME}
    quarkus.datasource.cashback.password=${DATASOURCE_password}

    kafka.customer.topic.name={{ .Values.kafka.topics.customer }}
    kafka.order.topic.name={{ .Values.kafka.topics.order }}

    cashback-service.url=http://{{ .Values.cashbackService.service }}:8080/expense

    kafka.customer.consumer.group={{ .Values.kafka.consumerGroup.customer }}
    kafka.order.consumer.group={{ .Values.kafka.consumerGroup.order }}
