inventoryService:
  name: inventory
  replicaCount: 1
  image:
    repository: quay.io/globex-recommendation/inventory
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "6500629"
  ports:
    httpPortName: http
    httpPort: 8080
  service:
    portName: http
    port: 8080
  route:
    enabled: false
    host:
    tlsEnabled: true
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

inventoryDb:
  name: inventory-database
  replicaCount: 1
  image:
    repository: quay.io/globex-recommendation/inventory-database
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0f2bc23"
  pgsqlUser: inventory
  pgsqlPassword: inventory
  pgsqlDatabase: inventory
  secret:
    name: inventory-database

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
