nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: quay.io/cloud-architecture-workshop/inventory-database
  pullPolicy: IfNotPresent
  tag: latest

podSecurityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

podAnnotations: {}

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  timeoutSeconds: 1
  initialDelaySeconds: 5
  tcpSocket:
    port: 5432

readinessProbe:
  timeoutSeconds: 1
  initialDelaySeconds: 5
  exec:
    command:
    - "/bin/sh"
    - "-i"
    - "-c"
    - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'

service:
  portName: postgresql
  port: 5432
  containerPort: 5432

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

pgsql:
  user: inventory
  password: inventory
  database: inventory

persistence:
  mode: persistent
  capacity: 5Gi

argocd:
  enabled: true
  syncwave: "-2"
