apiVersion: v2
name: globex
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: globex-store-app
    version: 0.1.0
    repository: file://globex-store-app
  - name: globex-db
    version: 0.1.0
    repository: file://globex-db
  - name: globex-ui
    version: 0.1.0
    repository: file://globex-ui
  - name: recommendation-engine
    version: 0.1.0
    repository: file://recommendation-engine
  - name: activity-tracking
    version: 0.1.0
    repository: file://activity-tracking
