apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "threescale-tenant-secret.name" . }}-hook
  labels:
    {{- include "threescale-tenant-secret.labels" . | nindent 4 }}    
  namespace: {{ .Values.threescale.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "threescale-tenant-secret.serviceAccountName" . }}-hook
  namespace: {{ .Release.Namespace }}
