nameOverride: ""
fullnameOverride: ""

service:
  port: 8080

route:
  enabled: true
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

database:
  vendor: postgres
  host: keycloak-db
  secret: keycloak-db
  ingress: false

argocd:
  enabled: true
  syncwave: "-1"