apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketchat.name" . }}
  labels:
    {{- include "rocketchat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: tcp-{{ .Values.service.port }}
  selector:
    {{- include "rocketchat.selectorLabels" . | nindent 4 }}
