hook:
  image:
    repository: quay.io/cloud-architecture-workshop/wait-for-routes-job
    pullPolicy: IfNotPresent
    tag: "d41c5da-native"
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  hostPattern: ""
  argocd:
    enabled: true
    syncwave: "-1"

loop:
  prefix: user
  count: 1