hook:
  pre:
    image:
      repository: quay.io/cloud-architecture-workshop/wait-for-routes-job
      pullPolicy: IfNotPresent
      tag: "d41c5da-native"
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    hostPattern: ""
    argocd:
      enabled: true
      syncwave: "-1"

  post:
    image:
      repository: quay.io/cloud-architecture-workshop/trigger-pipelines-job
      pullPolicy: IfNotPresent
      tag: "e5f0b58-native"
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    argocd:
      enabled: true
      syncwave: "0"

git:
  repo: https://github.com/btison/cms-api-example.git
  ref: main

cms:
  image: ghcr.io/fwmotion/3scale-cms:latest
  command: upload
  contextDir: ./developer-portal

loop:
  prefix: user
  count: 1