# Default values for element.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/cloud-architecture-workshop/element-web
  pullPolicy: IfNotPresent
  tag: "v1.11.38"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

resources: {}

livenessProbe:
  httpGet:
      path: /
      port: http
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
      path: /
      port: http
  initialDelaySeconds: 2
  periodSeconds: 3

synapse:
  url:
