apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.client.secret.name }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    camel.component.aws2-s3.accessKey={{ .Values.minio.accessKey }}
    camel.component.aws2-s3.secretKey={{ .Values.minio.secretKey }}
