kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "minio.name" . }}-pvc
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.pvc.storage }}
  storageClassName: {{ .Values.minio.pvc.storageClass }}
  volumeMode: Filesystem
