apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.name" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
