apiVersion: v1
kind: Service
metadata:
  name: {{ include "globex-ui.name" . }}
  labels:
    {{- include "globex-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.containerPort }}
  selector:
    {{- include "globex-ui.selectorLabels" . | nindent 4 }}
