keycloak:
  name: keycloak

realm:
  name: globex
  # Ids that are referenced multiple times in the template. Expected format: random ascii string, lenght 15
  globexWebGatewayContainerId:
  clientRealmManagementContainerId:
  clientBrokerContainerId:
  accountContainerId:

hook:
  image:
    repository: quay.io/cloud-architecture-workshop/wait-for-statefulset-job
    pullPolicy: IfNotPresent
    tag: "1c68180"
  serviceAccount:
    create: true
    name: ""
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  maxTimeToWait: 120000

argocd:
  enabled: true
  syncwave: "-2"
