replicaCount: 1
nameOverride: rocketchat-integration

broker:
  client:
    secret: client-amq
  amqp:
    connections: 5
    topic:
      clients: "support.rocketchat.client."
      agents: "support.rocketchat"

rocketchat:
  secret: rocketchat-webhook

argocd:
  enabled: true
  syncwave: "2"
