globexUi:
  name: globex-ui
  replicas: 1
  image: quay.io/globex-recommendation/globex-recommendation-ui:91c32a0
  imagePullPolicy: IfNotPresent
  serviceAccount: default
  ports:
    httpPortName: http
    httpPort: 8080
  service:
    portName: http
    port: 8080
  route:
    enabled: false
    host:
    tlsEnabled: true
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  env:
    nodeEnv: prod
    trackActivityService:
      url:
      postActivityPath:
    catalogService:
      url: 
      getProductsPath: 
      getProductListPath: 
    recommendationEngine:
      url: 
      getRecommendedProductsPath: 
  
