{{- if .Values.enabled -}}
---
apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  name: {{ include "integration-platform.name" . }}
  labels:
    {{- include "integration-platform.labels" . | nindent 4 }}
spec:
  build:
    buildStrategy: {{ .Values.buildStrategy }}
  kamelet: {}
  profile: OpenShift
  resources: {}
{{ end }}