apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: {{ .Values.inventoryService.name }}
    app.kubernetes.io/part-of: app-inventory
  name: {{ .Values.inventoryService.name }}
spec:
  replicas: {{ .Values.inventoryService.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.inventoryService.name }}
      app.kubernetes.io/part-of: app-inventory
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ .Values.inventoryService.name }}
        app.kubernetes.io/part-of: app-inventory
    spec:
      containers:
      - image: {{ .Values.inventoryService.image }}
        imagePullPolicy: {{ .Values.inventoryService.imagePullPolicy }}
        name: {{ .Values.inventoryService.name }}
        ports:
          - name: {{ .Values.inventoryService.ports.httpPortName }}
            containerPort: {{ .Values.inventoryService.ports.httpPort }}
            protocol: TCP
        resources: {}
        env:
          - name: QUARKUS_DATASOURCE_USERNAME
            value: {{ .Values.inventoryDb.pgsqlUser }}
          - name: QUARKUS_DATASOURCE_PASSWORD
            value: {{ .Values.inventoryDb.pgsqlPassword }}
          - name: QUARKUS_DATASOURCE_JDBC_URL
            value: jdbc:postgresql://{{ .Values.inventoryDb.name }}:5432/{{ .Values.inventoryDb.pgsqlDatabase }}
      serviceAccountName: {{ .Values.inventoryService.serviceAccount }}
      serviceAccount: {{ .Values.inventoryService.serviceAccount }}
