apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ .Values.catalogDb.name }}
    app.openshift.io/runtime: postgresql
    app.kubernetes.io/part-of: app-catalog
  name: {{ .Values.catalogDb.name }}
spec:
  replicas: {{ .Values.catalogDb.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.catalogDb.name }}
      app.kubernetes.io/part-of: app-catalog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ .Values.catalogDb.name }}
        app.kubernetes.io/part-of: app-catalog
        name: {{ .Values.catalogDb.name }}
    spec:
      containers:
      - image: {{ .Values.catalogDb.image }}
        imagePullPolicy: {{ .Values.catalogDb.imagePullPolicy }}
        name: {{ .Values.catalogDb.name }}
        ports:
          - name: postgresql
            containerPort: 5432
            protocol: TCP
        resources: {}
        env:
          - name: POSTGRESQL_USER
            value: {{ .Values.catalogDb.pgsqlUser }}
          - name: POSTGRESQL_PASSWORD
            value: {{ .Values.catalogDb.pgsqlPassword }}
          - name: POSTGRESQL_DATABASE
            value: {{ .Values.catalogDb.pgsqlDatabase }}
      serviceAccountName: {{ .Values.catalogDb.serviceAccount }}
      serviceAccount: {{ .Values.catalogDb.serviceAccount }}
