kind: Secret
apiVersion: v1
metadata:
  name: {{ include "integration.name" . }}-credentials
  labels:
    {{- include "integration.labels" . | nindent 4 }}
stringData:
  slack.properties: |
    # Slack
    slack.app.id={{ .Values.slack.appId }}
    slack.token.app={{ .Values.slack.token.app }}
    slack.token.bot={{ .Values.slack.token.bot }}
type: Opaque
