apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka.name" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "kafka.name" . }}
  namespace: {{ .Release.Namespace }}