apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-broker.name" . }}-client-secret
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "kafka-broker.labels" . | nindent 4 }}
  annotations:
    {{- include "kafka-broker.argocd-syncwave" . | nindent 4 }}
stringData:
  bootstrapServer: {{ include "kafka-broker.bootstrapServer" . }}
  securityProtocol: {{ .Values.authentication.securityProtocol }}
  saslMechanism: {{ .Values.authentication.saslMechanism }}
  clientId: {{ .Values.authentication.clientId }}
  clientSecret: {{ .Values.authentication.clientSecret }}
type: Opaque
