nameOverride: globex-camel-amq

image:
  repository: quay.io/cloud-architecture-workshop/amq-camel-secret-job
  pullPolicy: IfNotPresent
  tag: "21971cd-native"
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

amq:
  namespace: 
