apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "element.name" . }}
  labels:
    {{- include "element.labels" . | nindent 4 }}
data:
  config.json: |
    {
        "default_server_config": {
            "m.homeserver": {
                "base_url": "{{ .Values.synapse.url }}"
            }
        },
        "brand": "Element",
        "show_labs_settings": false,
        "room_directory": {
            "servers": []
        },
        "enable_presence_by_hs_url": {
            "https://matrix.org": false,
            "https://matrix-client.matrix.org": false
        },
        "features": {
            "feature_video_rooms": false
        },
        "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=fU3vlMsMn4Jb6dnEIFsx",
        "disable_3pid_login": true,
        "disable_login_language_selector": true,
        "disable_guests": true,
        "disable_custom_urls": true,
        "default_federate": false,
        "setting_defaults": {
            "UIFeature.feedback": false,
            "UIFeature.voip": false,
            "UIFeature.widgets": false,
            "UIFeature.advancedSettings": false,
            "UIFeature.shareQrCode": false,
            "UIFeature.shareSocial": false,
            "UIFeature.identityServer": false,
            "UIFeature.thirdPartyId": false,
            "UIFeature.registration": false,
            "UIFeature.passwordReset": false,
            "UIFeature.deactivate": false,
            "UIFeature.advancedEncryption": false,
            "UIFeature.roomHistorySettings": false,
            "UIFeature.locationSharing": false,
            "UIFeature.BulkUnverifiedSessionsReminder": false,
            "breadcrumbs": true
        }
    }
