{{- if .Values.route.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "element.name" . }}
  labels:
    {{- include "element.labels" . | nindent 4 }}
spec:
  {{ if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{ end }}
  to:
    kind: Service
    name: {{ include "element.name" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
  {{- if .Values.route.tlsEnabled }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  {{ end }}
{{ end }}