apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: {{ .Values.broker.name }}
  labels:
    {{- include "amq-broker.labels" . | nindent 4 }}
    application: broker-app
spec:
  acceptors:
    - name: amqp
      port: 5671
      protocols: amqp
      sslEnabled: true
      sslSecret: {{ .Values.broker.secret }}
  deploymentPlan:
    image: placeholder
    size: 1
    requireLogin: false
    persistenceEnabled: false
    journalType: nio
    messageMigration: false
    jolokiaAgentEnabled: false
    managementRBACEnabled: true
  adminUser: {{ .Values.broker.admin.user }}
  adminPassword: {{ .Values.broker.admin.password }}
