kind: Secret
apiVersion: v1
metadata:
  name: {{ include "globex-db-secret.name" . }}
  labels:
    {{- include "globex-db-secret.labels" . | nindent 4 }}
  annotations:
    {{- include "globex-db-secret.argocd-syncwave" . | nindent 4 }}
stringData:
  database-user: {{ .Values.pgsql.user }}
  database-password: {{ .Values.pgsql.password }}
  database-name: {{ .Values.pgsql.database }}
  database-admin-password: {{ include "globex-db-secret.admin-password" . }}
  database-debezium-password: {{ .Values.pgsql.debeziumPassword }}
type: Opaque
