replicaCount: 1

datagrid:
  name: globex-datagrid

identities:
  username: developer
  password: password

hook:
  image:
    repository: quay.io/cloud-architecture-workshop/datagrid-truststore-secret-job
    pullPolicy: IfNotPresent
    tag: "51a6ab5-native"
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  argocd:
    enabled: true
    syncwave: "1"
