apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.broker.name }}-console
spec:
  to:
    kind: Service
    name: {{ .Values.broker.name }}-hdls-svc
    weight: 100
  port:
    targetPort: console-jolokia
  wildcardPolicy: None
