apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ .Values.inventoryDb.name }}
    app.openshift.io/runtime: postgresql
    app.kubernetes.io/part-of: app-inventory
  name: {{ .Values.inventoryDb.name }}
spec:
  replicas: {{ .Values.inventoryDb.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.inventoryDb.name }}
      app.kubernetes.io/part-of: app-inventory
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ .Values.inventoryDb.name }}
        app.kubernetes.io/part-of: app-inventory
        name: {{ .Values.inventoryDb.name }}
    spec:
      containers:
        - image: {{ .Values.inventoryDb.image }}
          imagePullPolicy: {{ .Values.inventoryDb.imagePullPolicy }}
          name: {{ .Values.inventoryDb.name }}
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          resources: {}
          env:
            - name: POSTGRESQL_USER
              value: {{ .Values.inventoryDb.pgsqlUser }}
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.inventoryDb.pgsqlPassword }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.inventoryDb.pgsqlDatabase }}
      serviceAccountName: {{ .Values.inventoryDb.serviceAccount }}
      serviceAccount: {{ .Values.inventoryDb.serviceAccount }}
