{{- range untilStep 0 (.Values.numUsers | int64 | int) 1 }}
{{ $loop := printf "%s%s" $.Values.userPrefix ((add . 1) | toString) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: matrix-secret-job-{{ $loop }}
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: matrix-secret-job
  namespace: {{ $.Values.rolebinding.serviceAccountNamespace }}-{{ $loop }}
{{- end }}
