{{- if eq .Values.persistence.mode "persistent" -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "matrix-synapse.name" . }}-claim
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
{{- end }}