apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-synapse.name" . }}-config
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  homeserver.yaml: |-
    # Configuration file for Synapse.
    #
    # This is a YAML file: see [1] for a quick introduction. Note in particular
    # that *indentation is important*: all the elements of a list or dictionary
    # should have the same indentation.
    #
    # [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
    #
    # For more information on how to configure Synapse, including a complete accounting of
    # each option, go to docs/usage/configuration/config_documentation.md or
    # https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
    server_name: "{{ .Values.synapse.serverName }}"
    # public_baseurl: "https://synapse-service-matrix.apps.cluster-svdnn.svdnn.sandbox758.opentlc.com"
    pid_file: /data/homeserver.pid
    listeners:
      - port: {{ .Values.service.port }}
        tls: false
        type: http
        x_forwarded: true
        resources:
          - names: [client, federation]
            compress: false

    database:
      name: sqlite3
      args:
        database: /data/homeserver.db

    # database:
    #  name: psycopg2
    #  allow_unsafe_locale: true
    #  args:
    #    user: synapse-db
    #    password: synapse
    #     database: synapse
    #     host: postgres-service.test.svc.cluster.local
    #     cp_min: 5
    #     cp_max: 10

    # rate limiting
    rc_message:
      per_second: 50
      burst_count: 50


    log_config: "/data/{{ .Values.synapse.serverName }}.log.config"
    media_store_path: /data/media_store
    registration_shared_secret: "{{ .Values.synapse.registrationSharedSecret }}"
    report_stats: false
    macaroon_secret_key: "{{ .Values.synapse.macaroonSecretKey }}"
    form_secret: "{{ .Values.synapse.formSecretKey }}"
    signing_key_path: "/data/{{ .Values.synapse.serverName }}.signing.key"
    trusted_key_servers:
      - server_name: "matrix.org"

    enable_group_creation: true

    # vim:ft=yaml
  registration-secret: {{ .Values.synapse.registrationSharedSecret }}
