nameOverride: "kafka"

kafka:
  enabled: true
  version: 3.3.1
  cluster:
    replicas: 2
  zookeeper:
    replicas: 3
  config:
    autoCreateTopics: false
    defaultReplicationFactor: 2
    offsetsTopicReplicationFactor: 2
    transactionStateLogReplicationFactor: 2
    transactionStateLogMinIsr: 2
    minInsyncReplicas: 1
    interBrokerProtocolVersion: '3.3'

bootstrapServer:  

authentication:
  userId:
  userSecret:
  securityProtocol:
  saslMechanism: 

argocd:
  enabled: true
  syncwave: "-2"
